### ISSUE TITLE
Bug when using Mapzen instead of Mapbox

### ISSUE THREAD

**Issue by g12n** [ubergesundheit/ma-tiles#2]
I tried to feed a custom style to ma-tiles that uses the Vector Render Service by @mapzen instead of the @mapbox vector tiles. In Mapbox Studio it works fine using this URL als a remote layer source: http://vector.mapzen.com/osm/tilejson/mapbox.json

You can find my style here:
https://github.com/g12n/mapzen-slate.tm2

The renderer doesn‘t start with this style. I already verified this is due to the external datasource. Using a mapbox-source for this style works perfectly fine. 

```
Recreating matiles_renderer_1...
Attaching to matiles_renderer_1
renderer_1 |
renderer_1 | > ma-tiles@0.0.0 start /tilelive
renderer_1 | > coffee server.coffee
renderer_1 |
renderer_1 | starting server, please stand by!
renderer_1 | Listening on port: 8888
renderer_1 |
renderer_1 | /tilelive/server.coffee:39
renderer_1 |       throw err;
renderer_1 |             ^
renderer_1 | Error: Invalid tilesource protocol: http:
renderer_1 |   at Object.tilelive.load (/tilelive/node_modules/tilelive/lib/tilelive.js:96:25)
renderer_1 |   at new Backend (/tilelive/node_modules/tilelive-vector/backend.js:17:18)
renderer_1 |   at /tilelive/node_modules/tilelive-vector/index.js:104:25
renderer_1 |
renderer_1 |
renderer_1 | npm ERR! Linux 3.18.5-tinycore64
renderer_1 | npm ERR! argv "node" "/usr/local/bin/npm" "start"
renderer_1 | npm ERR! node v0.10.36
renderer_1 | npm ERR! npm  v2.5.0
renderer_1 | npm ERR! code ELIFECYCLE
renderer_1 | npm ERR! ma-tiles@0.0.0 start: `coffee server.coffee`
renderer_1 | npm ERR! Exit status 8
renderer_1 | npm ERR!
renderer_1 | npm ERR! Failed at the ma-tiles@0.0.0 start script 'coffee server.coffee'.
renderer_1 | npm ERR! This is most likely a problem with the ma-tiles package,
renderer_1 | npm ERR! not with npm itself.
renderer_1 | npm ERR! Tell the author that this fails on your system:
renderer_1 | npm ERR!     coffee server.coffee
renderer_1 | npm ERR! You can get their info via:
renderer_1 | npm ERR!     npm owner ls ma-tiles
renderer_1 | npm ERR! There is likely additional logging output above.
renderer_1 |
renderer_1 | npm ERR! Please include the following file with any support request:
renderer_1 | npm ERR!     /tilelive/npm-debug.log
matiles_renderer_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by ubergesundheit** [comment]
I think http must be registered as protocoll in tilelive. I will definitely look into this!!

**Comment by ubergesundheit** [comment]
I think commit 13786d459 should fix this! Please test and report back! Thanks for figuring out how to use the mapzen source in mapbox studio!

**Comment by g12n** [comment]
Ah great! It works! :) 
You can see a sample here: https://github.com/g12n/ma-tiles/tree/feature/mapzen-slate

Thank you!

**Comment by ubergesundheit** [comment]
:+1:
